# Site settings
title: King David
description: '"Making Good Men Better"'
url: 'http://kingdavid407.github.io'
baseurl: '/'
theme: jekyll-theme-feeling-responsive
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'King David'
  email: kingdavidlodge407@gmail.com

